name: Chats

on:
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout GPT Store backup
      uses: actions/checkout@v2
      with:
        repository: airyland/gptshunter-v2
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: 'gptshunter-v2'

    - uses: actions/setup-node@v3

    - name: Cache Yarn dependencies
      uses: actions/cache@v2
      with:
        path: |
          .yarn/cache
          .yarn/unplugged
          .yarn/build-state.yml
          .yarn/install-state.gz
          node_modules
          ~/.cache/ms-playwright/
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        cd gptshunter-v2
        yarn add dayjs @libsql/client playwright
    - name: Install playwright browsers
      run: npx playwright install --with-deps

    - name: Get chats
      run: |
        cd gptshunter-v2
        node scripts/get_chats.cjs
